#!/bin/bash
command -v npm >/dev/null 2>&1 || { echo >&2 "npm not found. Please install node/npm."; exit 1; }
echo Installing socket.io...
npm install -g socket.io
echo Linking socket.io to the local project...
npm link socket.io
echo Installing express...
npm install -g express
echo Linking express to the local project...
npm link express
echo Installing phonegap...
npm install -g phonegap
echo Installing cordova...
npm install -g cordova